name: Build a Release
on: 
   push:
jobs:
  BuildRelease:
   runs-on: ubuntu-latest    
   steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
 
    - uses: 8BitJonny/gh-get-current-pr@2.1.3
      id: PR
      # Psuhing to the PR
      # Did it work?
      # maybe it needed to be in the master
      #pushing to a pull request
    - run: cat ${{ steps.PR.outputs.pr_body }}

