name: Build a Release
on: 
   push:
jobs:
  BuildRelease:
   runs-on: ubuntu-latest    
   steps:
    - uses: actions/checkout@v3
    - uses: 8BitJonny/gh-get-current-pr@2.1.3
      id: PR
    - run: |
        multiline="${{ steps.PR.outputs.pr_body }}"
        echo ${multiline/$'\n'/}
    - uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "CHANGELOG"
        replace: ${{ steps.PR.outputs.pr_body }}
        include: metadata.json
    - run: |
        sed -zi 's/\r\n/\\n/g' metadata.json
        sed -zi 's/\n//g' metadata.json
        cat metadata.json
        cat metadata.json | wc -l
    

