name: Build a Release
on: 
   push:
jobs:
  BuildRelease:
   runs-on: ubuntu-latest    
   steps:
    - uses: 8BitJonny/gh-get-current-pr@2.1.3
      id: PR
    - run: |
        TBD='${{ steps.PR.outputs.pr_body }}'
        echo $TBD
        sudo sed -i "s/CHANGELOG/$TBD/g" metadata.json

