name: Build a Release
on: 
   push:
jobs:
  BuildRelease:
   runs-on: ubuntu-latest    
   steps:
    - uses: 8BitJonny/gh-get-current-pr@2.1.3
      id: PR
    - run: |
        echo ${{ steps.PR.outputs.pr_body }}

